### ISSUE TITLE
Git Commit Error ***Please tell me who you are.

### ISSUE THREAD

**Issue by Dvnwllms** [nielsenjared/git-troubleshoot#4]
$ git commit

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'dvnwl@DESKTOP-8H2JHEK.(none)')

**Comment by nielsenjared** [comment]
We worked this out and it was more than this, but here's this issue addressed in the README https://github.com/nielsenjared/git-troubleshoot/blob/master/README.md#-please-tell-me-who-you-are
