### ISSUE TITLE
All things GIt

### ISSUE THREAD

**Issue by ccrawford90** [nielsenjared/git-troubleshoot#5]
git add
git commit
git push 

fatal: Not a git repository (or any of the parent directories): .git

**Comment by 4n4st4s14** [comment]
Make sure you have changed directories (cd) into the directory associated with your github repo. Then run:
git add filename (press return)
git commit -m "commit message" (press return)
git push (press return)

**Comment by nielsenjared** [comment]
Added solutions to README. See https://github.com/nielsenjared/git-troubleshoot/blob/master/README.md#fatal-not-a-git-repository-or-any-of-the-parent-directories-git
