### ISSUE TITLE
Misunderstanding

### ISSUE THREAD

**Issue by peakcodes** [nielsenjared/git-troubleshoot#6]
Timothys-MacBook-Pro:thistest timothyhill$ git push
Username for 'https://github.com': peakcodes
Password for 'https://peakcodes@github.com': 
To https://github.com/peakcodes/thistest.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/peakcodes/thistest.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push

**Comment by nielsenjared** [comment]
I updated the README to address this. Open a new issue if you encounter this in the future but are unable to resolve it with `git pull`

**Comment by nielsenjared** [comment]
https://github.com/nielsenjared/git-troubleshoot/blob/master/README.md#error-failed-to-push-some-refs
