### ISSUE TITLE
Error messages when using git add and git diff commands

### ISSUE THREAD

**Issue by Jongtelles** [nielsenjared/git-troubleshoot#8]
Received the error messages below when using git add and git diff commands during the git-basics exercise.

Jon@Jon-Lappy MINGW32 ~/apps/git-basics (master)
$ git add index.html
warning: CRLF will be replaced by LF in index.html.
The file will have its original line endings in your working directory.

Jon@Jon-Lappy MINGW32 ~/apps/git-basics (master)
$ git diff
warning: CRLF will be replaced by LF in index.html.
The file will have its original line endings in your working directory.
diff --git a/index.html b/index.html
index 34e83d7..9fbe182 100644
--- a/index.html
+++ b/index.html
@@ -5,6 +5,6 @@
     <title></title>
   </head>
   <body>
-
+    <h1>I love Git!</h1>
   </body>
 </html>
\ No newline at end of file

**Comment by Jongtelles** [comment]
Found this explaining it, seems like it's a windows thing: https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important

**Comment by nielsenjared** [comment]
Added to README https://github.com/nielsenjared/git-troubleshoot/blob/master/README.md#windowsgit-bash-specific

The Google Fu is strong with you.
