### ISSUE TITLE
unable to pull class repo

### ISSUE THREAD

**Issue by Sishito** [nielsenjared/git-troubleshoot#9]
$ git pull
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by nielsenjared** [comment]
Git provides hints as to how to resolve this issue:
```
hint: Fix them up in the work tree, and then use 'git add/rm '
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```
You created, edited and/or deleted files locally and your repo is now out of sync with the remote. You need to either add the files or remove them. You most likely want to keep them, so:
```
git add -A
git commit -m "resolving pull conflict"
git pull
```
